### ISSUE TITLE
Release available?

### ISSUE THREAD

**Issue by lukruh** [dragonboy144/dsa#1]
Hey, gibts nen release oder kann man irgendwie an die APK kommen ohne es selbst bauen zu müssen?

**Comment by dragonboy144** [comment]
Hallo, nein es gibt keine APK, da ich die android version noch nicht funktionsfähig gemacht hab, ehrlich gesagt hab ich das auch nicht in allzu naher  zeit geplant gehabt, da dieses Tool erstmal nur als Spielhillfe für meine DSA gruppe dienen sollte, ich hätte nicht damit gerechnet das jemand diese Repository entdeckt. Wenn sie wollen kann ich ihnen die .exe schicken, aktuell ist halt nur der Steigerungsrechner funktionsfähig und sieht so aus:
![SteigerungsTool](https://user-images.githubusercontent.com/43814031/128507562-6fa00798-02ea-4505-b174-74098db5c9aa.PNG)
